### ISSUE TITLE
Beatsaver's site had some updates

### ISSUE THREAD

**Issue by NustyFrozen** [lolPants/BeatSaverSharp#4]
Beatsaver's site had some updates due to their recent problems and crashes

so this library doesn't function anymore what my problem was when first noticing was: "BeatSaver.Client.Search()" function any query will give the exception: Unexpected character encountered while parsing value: e. Path '', line 0, position 0

lulu please update it plz owo

**Comment by lolPants** [comment]
BeatSaverSharp v1.x is EOL and feature frozen until v2 is released. I would advise testing this bug on v2 (grab the latest `.dll` from [Actions](https://github.com/lolPants/BeatSaverSharp/actions))

If the bug is still present feel free to update this issue.

**Comment by NustyFrozen** [comment]
thank you! fixed my problem
